// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTXv_AaGwaKx3iXbEq4mbxTa0yY48zTsw',
    appId: '1:807122381494:web:d01c31a1f321e85c769417',
    messagingSenderId: '807122381494',
    projectId: 'garsonapp-1d821',
    authDomain: 'garsonapp-1d821.firebaseapp.com',
    storageBucket: 'garsonapp-1d821.firebasestorage.app',
    measurementId: 'G-3TGHSJGNWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW8RoYAxDYzF6demjeV5UIeF8wm5HZELA',
    appId: '1:807122381494:android:c541ee974ba3b90b769417',
    messagingSenderId: '807122381494',
    projectId: 'garsonapp-1d821',
    storageBucket: 'garsonapp-1d821.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8KzQnz5NGg-BjCNW0zuMV0sq87CDcBnY',
    appId: '1:807122381494:ios:c2842fcb42a9ca37769417',
    messagingSenderId: '807122381494',
    projectId: 'garsonapp-1d821',
    storageBucket: 'garsonapp-1d821.firebasestorage.app',
    iosBundleId: 'com.garsonapp.garsonapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8KzQnz5NGg-BjCNW0zuMV0sq87CDcBnY',
    appId: '1:807122381494:ios:c2842fcb42a9ca37769417',
    messagingSenderId: '807122381494',
    projectId: 'garsonapp-1d821',
    storageBucket: 'garsonapp-1d821.firebasestorage.app',
    iosBundleId: 'com.garsonapp.garsonapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTXv_AaGwaKx3iXbEq4mbxTa0yY48zTsw',
    appId: '1:807122381494:web:3301a1ff411a69aa769417',
    messagingSenderId: '807122381494',
    projectId: 'garsonapp-1d821',
    authDomain: 'garsonapp-1d821.firebaseapp.com',
    storageBucket: 'garsonapp-1d821.firebasestorage.app',
    measurementId: 'G-C8XEDVC2KJ',
  );
}
